- name: modify repository php5.6
  apt_repository:
    repo: "ppa:ondrej/php5-5.6"
    state: present
  when: "{{ php_version | version_compare('5.6', '==') }}"

- name: install php5-fpm
  apt:
    name: "{{ item }}={{ php_version }}*"
    state: present
    force: yes
  with_items:
    - "php5-fpm"
    - "php5-gd"
    - "php5-mysql"
    - "php5-pgsql"
  notify: restart php5-fpm

- name: modify config
  template:
    src: "{{ item }}"
    dest: "/etc/php5/fpm/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - php-fpm.conf
    - php.ini
  notify: restart php5-fpm

- name: php5-fpm is enabled
  service:
    name: php5-fpm
    state: started
    enabled: yes
